/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.master.interfacegf;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
//import javafx.scene.layout.Border;
//import javax.jws.WebParam;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Nairon
 */
public class JanelaExtrato extends javax.swing.JFrame {

	/**
	 * Creates new form JanelaExtrato
	 */
	public JanelaExtrato(ArrayList<String> extrato) {
		initComponents();
		DefaultListModel model = new DefaultListModel();
		for (int i = 0; i < extrato.size(); i++) {
			model.addElement(extrato.get(i));
		}
		jList1.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButtonVoltar02 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setLocation(new java.awt.Point(350, 100));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("Extrato Bancário");

		jButtonVoltar02.setText("Voltar");
		jButtonVoltar02.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVoltar02ActionPerformed(evt);
			}
		});

		jScrollPane1.setViewportView(jList1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(127, 127, 127)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191,
												Short.MAX_VALUE)
										.addComponent(jButtonVoltar02).addGap(21, 21, 21))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(21, 21, 21).addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
						.addComponent(jButtonVoltar02).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonVoltar02ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVoltar02ActionPerformed

		dispose();

	}// GEN-LAST:event_jButtonVoltar02ActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonVoltar02;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList<String> jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
