/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.master.interfacegf;

import bank.master.classes.Conta;
import bank.master.classes.LoginConta;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nairon
 */
public class JanelaSacar extends javax.swing.JFrame {

	/**
	 * Creates new form JanelaSacar
	 */
	public JanelaSacar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		lblStatus = new javax.swing.JLabel();
		buttonFechar = new javax.swing.JButton();

		jLabel4.setText("jLabel4");

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setLocation(new java.awt.Point(350, 100));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setText("Valor do saque (R$) : ");

		jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jButton1.setText("Sacar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		buttonFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		buttonFechar.setText("Fechar");
		buttonFechar.setActionCommand("Fechar");
		buttonFechar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonFecharActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(39, 39, 39).addComponent(jLabel2)
								.addGap(30, 30, 30).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										141, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(137, 137, 137).addComponent(jLabel1))
						.addGroup(layout.createSequentialGroup().addGap(149, 149, 149).addComponent(jButton1))
						.addGroup(layout.createSequentialGroup().addGap(158, 158, 158).addComponent(jLabel3))
						.addGroup(layout.createSequentialGroup().addGap(20, 20, 20).addComponent(lblStatus,
								javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(56, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE).addComponent(buttonFechar).addGap(28, 28, 28)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jButton1).addGap(89, 89, 89).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblStatus)
						.addGap(26, 26, 26).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
						.addComponent(buttonFechar).addGap(30, 30, 30)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		double valor = Double.parseDouble(jTextField1.getText());
		Conta conta = new Conta();
		try {
			conta.carregarDados(LoginConta.sessao, LoginConta.numConta);
			if (conta.sacar(valor)) {
				JOptionPane.showMessageDialog(null, "Saque de R$ " + valor + " realizado com sucesso!!");
				dispose();
			} else {
				JOptionPane.showMessageDialog(null, "Erro ao realizar saque!");
			}
		} catch (IOException ex) {
			Logger.getLogger(JanelaSacar.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonFecharActionPerformed

		dispose();

	}// GEN-LAST:event_buttonFecharActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonFechar;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JLabel lblStatus;
	// End of variables declaration//GEN-END:variables
}
