/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.master.interfacegf;

import bank.master.classes.CadastrarConta;

import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author Nairon
 */
public class JanelaCriarConta extends javax.swing.JFrame {

	/**
	 * Creates new form JanelaCriarConta
	 */
	public JanelaCriarConta() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		campoNomeCompleto = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		campoCPF = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		buttonCriarConta = new javax.swing.JButton();
		campoSenha = new javax.swing.JPasswordField();

		setLocation(new java.awt.Point(350, 100));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Abra agora sua Conta");

		jLabel2.setText("Nome Completo");

		campoNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				campoNomeCompletoActionPerformed(evt);
			}
		});

		jLabel3.setText("Numero do CPF");

		jLabel4.setText("Senha");

		buttonCriarConta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		buttonCriarConta.setText("Criar Conta");
		buttonCriarConta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCriarContaActionPerformed(evt);
			}
		});

		campoSenha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				campoSenhaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(29, 29, 29)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel4).addComponent(jLabel3).addComponent(jLabel2)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(campoNomeCompleto).addComponent(campoCPF).addComponent(campoSenha,
												javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(131, 131, 131).addComponent(buttonCriarConta)))
				.addContainerGap(74, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(campoNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(23, 23, 23).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(26, 26, 26).addComponent(jLabel4)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
				.addComponent(buttonCriarConta).addGap(38, 38, 38)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void campoNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNomeCompletoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_campoNomeCompletoActionPerformed

	private void buttonCriarContaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCriarContaActionPerformed

		String nome = campoNomeCompleto.getText();
		String senha = String.copyValueOf(campoSenha.getPassword());
		String cpf = campoCPF.getText();

		try {
			CadastrarConta criar = new CadastrarConta(nome, cpf, senha);

			criar.craiandoConta();
			dispose();
			JOptionPane.showMessageDialog(null,
					"PARABÉNS, CONTA CRIADA COM SUCESSO!! \nNúmero da sua conta : " + criar.getNumconta());

		} catch (IOException e) {
			e.printStackTrace();
		}
		InicioLogin ini = new InicioLogin();
		ini.setVisible(true);

	}// GEN-LAST:event_buttonCriarContaActionPerformed

	private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoSenhaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_campoSenhaActionPerformed

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCriarConta;
	private javax.swing.JTextField campoCPF;
	private javax.swing.JTextField campoNomeCompleto;
	private javax.swing.JPasswordField campoSenha;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables
}
