/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.master.interfacegf;

import bank.master.classes.Conta;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nairon
 */
public class JanelaDepositar extends javax.swing.JFrame {

	/**
	 * Creates new form JanelaDepositar
	 */
	public JanelaDepositar() {

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		destinatario = new javax.swing.JTextField();
		jButtonContinuar = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		valordeposi = new javax.swing.JTextField();

		setLocation(new java.awt.Point(350, 100));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("Numero da conta do destinatário:");

		destinatario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				destinatarioActionPerformed(evt);
			}
		});

		jButtonContinuar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButtonContinuar.setText("Continuar");
		jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonContinuarActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setText("Valor do depósito (R$):");

		valordeposi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				valordeposiActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(172, 172, 172).addComponent(jLabel3))
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jButtonContinuar)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(destinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 147,
												Short.MAX_VALUE)
										.addComponent(valordeposi))))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(29, 29, 29)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(valordeposi, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jLabel3).addGap(58, 58, 58).addComponent(jButtonContinuar)
				.addContainerGap(80, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void destinatarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_destinatarioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_destinatarioActionPerformed

	private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonContinuarActionPerformed
		int numero = Integer.parseInt(destinatario.getText());
		double value = Double.parseDouble(valordeposi.getText());

		Conta conta = new Conta();
		try {

			JanelaConfirmaDeposito confirmaDeposito = new JanelaConfirmaDeposito(conta.depositar(numero, value, false),
					numero, value);
			// jDesktopPane2.add(confirmaDeposito);
			confirmaDeposito.setVisible(true);
			dispose();
		} catch (IOException ex) {
			Logger.getLogger(JanelaDepositar.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jButtonContinuarActionPerformed

	private void valordeposiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_valordeposiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_valordeposiActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField destinatario;
	private javax.swing.JButton jButtonContinuar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField valordeposi;
	// End of variables declaration//GEN-END:variables
}
