/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.master.interfacegf;

import bank.master.classes.Conta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nairon
 */
public class JanelaConfirmaDeposito extends javax.swing.JFrame {
	int numero = 0;
	double valor = 0;

	/**
	 * Creates new form JanelaConfirmaDeposito
	 */
	public JanelaConfirmaDeposito(ArrayList<String> arrayConfirma, int numero, double valor) {

		initComponents();
		nomecompleto.setText("Nome Completo : " + arrayConfirma.get(0));
		numeroconta.setText("Numero da Conta : " + arrayConfirma.get(2));
		this.numero = numero;
		this.valor = valor;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		buttonConfirma = new javax.swing.JButton();
		nomecompleto = new javax.swing.JLabel();
		numeroconta = new javax.swing.JLabel();
		cancelar = new javax.swing.JButton();

		setLocation(new java.awt.Point(350, 100));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("Confirme as informações do destinatário");

		buttonConfirma.setText("Confirmar");
		buttonConfirma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonConfirmaActionPerformed(evt);
			}
		});

		nomecompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		numeroconta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		cancelar.setText("Cancelar");
		cancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(nomecompleto,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addComponent(jLabel1).addContainerGap(120,
						Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap().addComponent(numeroconta,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(67, 67, 67).addComponent(cancelar)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(buttonConfirma).addGap(67, 67, 67)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(nomecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(numeroconta, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buttonConfirma).addComponent(cancelar))
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonConfirmaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonConfirmaActionPerformed
		Conta conta = new Conta();
		try {
			String mensagem = conta.depositar(numero, valor, true).get(0);
			JOptionPane.showMessageDialog(null, mensagem);
		} catch (IOException ex) {
			Logger.getLogger(JanelaConfirmaDeposito.class.getName()).log(Level.SEVERE, null, ex);
		}
		dispose();
	}// GEN-LAST:event_buttonConfirmaActionPerformed

	private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelarActionPerformed
		dispose();
	}// GEN-LAST:event_cancelarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonConfirma;
	private javax.swing.JButton cancelar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel nomecompleto;
	private javax.swing.JLabel numeroconta;
	// End of variables declaration//GEN-END:variables
}
